import FlutterMacOS
import Foundation

// macOS stub — KIVO uses a bundled ffmpeg binary on desktop.
// This file exists only to satisfy the module import generated by Flutter.
public class FFmpegKitFlutterPlugin: NSObject, FlutterPlugin {
  public static func register(with registrar: FlutterPluginRegistrar) {
    // No-op on macOS.
  }
}
